# snmpagent config
snmp:
    - asyncnum: 100
    - timeout: 2
    - retry: 1
    - maxsesspool: 1000
    - maxlifetime: 30
http:
    - port: 1216
log:
    - logdir: "F:\\"
    - debug: true
    - logarchsize: 1048576
